id: P92A2F17A
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: zh
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    59a8dc89b97d4581b2cbe0ed70e94c64:
      title: Advice for Retreat
      parent: Advice
    ed2d05ab1ab54e1d80b88f8ae8b21ea1:
      title: Advice for Tenzin Jamchen
      parent: Advice
    1967587e16dc4eafb73d53820836ea4f:
      title: Advice in Four Lines
      parent: Advice
    61a908a20ad841d7bb2a97bdd9db2f19:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    f36721df2ce94faaadf9b020202da2df:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    e9107472e8614a00be8c3c147843c85e:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    e4e742236f444ec69a36d64e30906c55:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    cdd708319a194c8c9ad7fe36d15fbac3:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    fc04a0f190a24c85830063ebaafb72ae:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    c63267bcde07479b873209f0c9f57d90:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    7050401e413b4597bf53fc9c94755154:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    006973639ae34c57a7745acd20719812:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    52077b3dcb714b86ba7e1453da402d16:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    17907fccc87c40e28825819b5725dbd1:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    b6dca9e6e2234f8db119b8b8eeb812dc:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    aaa6f238e5744fc1b34ac82396060ba7:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    b4bf9d002c604d3a9817b76b885793c4:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    7df6206b0a0348d2b8a18322a10c5fed:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    6d4b5fa6edfc40319b1e9c93b052cdf6:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    09a55ee9528c4ae08517292d45b04dd2:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    46299d7a97324064a669c3d4481f4d71:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    ed53f20dba284f79a09e21b16ec41562:
      title: Verses of Homage
      parent: Praise
    19dcd37acbbf4da7abda5bab30a7c739:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    07a63cb732bf4c44aa402286d96947ab:
      title: A Record of the Successive Incarnations
      parent: Prayers
    1c17f4f3f87c4b2bb354e13b98862d66:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    1d9827846f5146b3a04c4eeb474456ac:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    2699e9a3570f472ca7b77a0957bc517c:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.297238'
last_modified_at: '2022-03-01T01:52:59.297241'
